# Spring Application Configuration
spring.application.name=InventoryGenius
spring.datasource.url=jdbc:postgresql://localhost:5432/inventorymanagement
spring.config.import=optional:application-secrets.properties
spring.datasource.username=postgres
#spring.datasource.password=AndyLove@123
spring.datasource.password=AndyLove@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# GitHub OAuth2 Configuration
spring.security.oauth2.client.registration.github.client-id=Ov23liU6Fv9uStJHrO21
spring.security.oauth2.client.registration.github.client-secret=808c60858213536c10b6829b7e2266f5c1873f5d
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user

spring.security.oauth2.client.provider.github.user-name-attribute=id

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID_DEV}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET_DEV}
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,email,profile


spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo

# To allow the cookie with session ID to pass to frontend
server.servlet.session.cookie.same-site=NONE
server.servlet.session.cookie.secure=true

server.servlet.session.tracking-modes=cookie
server.servlet.session.cookie.http-only=true


logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Ov23liU6Fv9uStJHrO21
# 808c60858213536c10b6829b7e2266f5c1873f5d